blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/VesperAkshay/lexora/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/VesperAkshay/lexora/blob/main/README.md
    about: Read the full documentation
  - name: 🚀 Getting Started Guide
    url: https://github.com/VesperAkshay/lexora/blob/main/docs/GETTING_STARTED.md
    about: Learn how to get started with Lexora
