name: ❓ Question / Help
description: Ask a question or get help using Lexora
title: "[Question]: "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide as much context as possible.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to accomplish?
      placeholder: I'm trying to build a system that...
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What have you already attempted?
      placeholder: I tried...
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Relevant Code
      description: Share any relevant code snippets
      render: python
      placeholder: |
        from lexora import RAGAgent
        
        # Your code here
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Getting Started
        - Configuration
        - Vector Databases
        - LLM Integration
        - RAG Tools
        - Custom Tools
        - Performance
        - Deployment
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Additional context...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the documentation and couldn't find an answer
          required: true
        - label: I have searched existing issues for similar questions
          required: true
